#!/usr/bin/env bash

sudo pacman -Syu
mkdir -p ~/clones/ ~/Documents/dev/ ~/Downloads/programs/ ~/Downloads/software/

# install from list 
sudo pacman -S curl git wget firefox gparted refind alacritty fish vlc mpv python xdotool flameshot copyq ffmpeg scrcpy tmux neovim qtile -y

# In fish
git clone --bare git@github.com:tusqasi/my_all_dot_files.git ~/.cfg

/usr/bin/git --git-dir=/home/tusqasi/.cfg/ --work-tree=/home/tusqasi checkout master

# tmux setup
git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
~/.config/tmux/plugins/tpm
