#!/usr/bin/env python
import sys
import utils
import libtmux
import os
from time import sleep
from pathlib import Path
from rich import print as p
from rich import inspect
from pyfzf.pyfzf import FzfPrompt


# make tmux sesion
# go to a given path
# open neovim with all files in lib/*

"""
Assume a project is  folder with this structure 

project_name
\_ main git repo
|   |
|    \_ worktrees
|
 \_ backend/other
    |
    \_ worktrees 
 
"""


PROJECT_PATH = Path("~/Documents/dev/digitize/app")

PROJECT_NAME = "flutter_project"
WORKTREE = sys.argv[1] if len(sys.argv) == 2 else None


def main(
    project_path: Path = Path("~/Documents/dev/digitize/"),
    project_name: str = "flutter_project",
    worktree: str = None,
):
    server = libtmux.Server()
    start_directory = Path(
        os.path.join(project_path, "worktrees", worktree) if worktree else project_path
    ).expanduser()
    print(start_directory)
    if not start_directory.exists():
        print(f"~{start_directory.relative_to(Path('~'))=} doesn't exist")

    if ses := server.find_where({"session_name": project_name}):
        print(f"{project_name} session exists")
        ses.switch_client()
        return
    else:
        print(f"Creating session {project_name} at {start_directory}")
        server.new_session(
            session_name=project_name,
            start_directory=start_directory,
            window_command="""nvim -c 'lua require"functions".flutter_start("linux")' `find lib -type f`""",
        ).switch_client()


if __name__ == "__main__":
    main(project_path=PROJECT_PATH, project_name=PROJECT_NAME, worktree=WORKTREE)
