#!/usr/bin/env bash

~/scripts/keyboard_setup &
unclutter -idle 5 &
lxpolkit &
volctl &
nm-applet &
picom &
feh ~/Pictures/Wallpapers/light_mode/graymountains.jpg --bg-fill &
copyq &
alacritty -e tmux new-session -A -s "sys" &
brave --force-device-scale-factor=1.25 &
~/scripts/battery_notify.py &
